import { IWItem } from "./types"
import knife_icon from "./assets/workshop/guns/knife.png"
import rod_icon from "./assets/workshop/guns/rod.png"
import staff_icon from "./assets/workshop/guns/staff.png"
import sword_icon from "./assets/workshop/guns/sword.png"
import wand_icon from "./assets/workshop/guns/wand.png"
import fire_icon from "./assets/workshop/artifacts/fire.png"
import acid_blob_icon from "./assets/workshop/being/acid_blob.png"
import cornuthaum_icon from "./assets/workshop/clothes/cornuthaum.png"
import cloud_calc_dust_1 from "./assets/workshop/elements/cloud_calc_dust_1.png"
import cloud_calc_dust_2 from "./assets/workshop/elements/cloud_calc_dust_2.png"
import cloud_calc_dust_3 from "./assets/workshop/elements/cloud_calc_dust_3.png"
import apple_icon from "./assets/workshop/food/apple.png"
import bone_icon from "./assets/workshop/other/bone.png"
import azure_icon from "./assets/workshop/plants/azure.png"
import white_potion_icon from "./assets/workshop/potion/white.png"
import black_potion_icon from "./assets/workshop/potion/black.png"
import altar_base_icon from "./assets/workshop/rock/altar_base.png"
import rune_abyss_icon from "./assets/workshop/runes/rune_abyss.png"
import sky_blue_icon from "./assets/workshop/potion/sky_blue.png"
import misc_horn_icon from "./assets/workshop/other/misc_horn.png"
import briar_patch_icon from "./assets/workshop/plants/briar_patch.png"
import bush_icon from "./assets/workshop/plants/bush.png"
import misc_disc_icon from "./assets/workshop/rock/misc_disc.png"
import rune_cerebov_icon from "./assets/workshop/runes/rune_cerebov.png"
import key_icon from "./assets/workshop/other/key.png"
import chest_icon from "./assets/workshop/other/chest_2_closed.png"
import scroll_purple_icon from "./assets/chest/scroll-purple.png"
import scroll_red_icon from "./assets/chest/scroll-red.png"
import scroll_blue_icon from "./assets/chest/scroll-blue.png"
import scroll_epic_icon from "./assets/chest/scroll_new.png"
import scroll_cyan_icon from "./assets/chest/scroll-cyan.png"
import scroll_yellow_icon from "./assets/chest/scroll-yellow.png"
import bookmark_icon from "./assets/chest/!bookmark_new.png"
import buckle_icon from "./assets/chest/!buckle_new.png"
import copper_icon from "./assets/chest/!copper.png"
import plaid_icon from "./assets/chest/!plaid_new.png"
import velvet_icon from "./assets/chest/!velvet_new.png"
import white_icon from "./assets/chest/!white_new.png"
import bone_gray_icon from "./assets/chest/bone_gray.png"
import book_of_the_dead_icon from "./assets/chest/book_of_the_dead_new.png"
import bronze_icon from "./assets/chest/bronze.png"
import celtic_red_icon from "./assets/chest/celtic_red.png"
import emerald_icon from "./assets/chest/emerald.png"
import eye_magenta_icon from "./assets/chest/eye_magenta.png"
import generic_icon from "./assets/chest/generic.png"
import glittering_icon from "./assets/chest/glittering.png"
import gold_icon from "./assets/chest/gold.png"
import manual_1_icon from "./assets/chest/manual_1.png"
import manual_2_icon from "./assets/chest/manual_2.png"
import misc_book_icon from "./assets/chest/misc_book.png"
import ring_black_onyx_icon from "./assets/chest/ring_black_onyx.png"
import ruby_icon from "./assets/chest/ruby.png"
import steel_icon from "./assets/chest/steel.png"
import stone_2_blue_icon from "./assets/chest/stone_2_blue.png"
import stone_3_magenta_icon from "./assets/chest/stone_3_magenta.png"
import urand_air_icon from "./assets/chest/urand_air_new.png"
import urand_bloodlust_icon from "./assets/chest/urand_bloodlust_new.png"
import urand_octoring_icon from "./assets/chest/urand_octoring.png"
import urand_shadows_icon from "./assets/chest/urand_shadows_new.png"
import urand_vitality_icon from "./assets/chest/urand_vitality.png"
import orange_icon from "./assets/workshop/food/orange.png"
import cheese_icon from "./assets/workshop/food/cheese.png"
import chunk_icon from "./assets/workshop/food/chunk.png"
import lemon_icon from "./assets/workshop/food/lemon.png"
import pizza_icon from "./assets/workshop/food/pizza.png"
import bubbly_icon from "./assets/workshop/potion/bubbly.png"
import potion_bubbly_icon from "./assets/workshop/potion/potion_bubbly.png"
import puce_icon from "./assets/workshop/potion/puce.png"
import ruby_potion_icon from "./assets/workshop/potion/ruby.png"
import stonesoup_icon from "./assets/workshop/potion/stonesoup.png"
import starcursed_mass_icon from "./assets/workshop/being/starcursed_mass.png"
import chaos_spawn_icon from "./assets/workshop/being/chaos_spawn.png"
import macabre_mass_icon from "./assets/workshop/plants/macabre_mass.png"
import tentacled_monstrosity_icon from "./assets/workshop/being/tentacled_monstrosity.png"
import chaos_spawn_4_icon from "./assets/workshop/being/chaos_spawn_4.png"
import chaos_spawn_3_icon from "./assets/workshop/being/chaos_spawn_3.png"
import thin_icon from "./assets/workshop/other/thin.png"
import thorn_lotus_icon from "./assets/workshop/plants/thorn_lotus.png"
import plant_icon from "./assets/workshop/plants/plant.png"
import thorn_hunter_icon from "./assets/workshop/plants/thorn_hunter.png"
import giant_spore_icon from "./assets/workshop/plants/giant_spore.png"
import plant_demonic_icon from "./assets/workshop/plants/plant_demonic.png"
import shining_eye_icon from "./assets/workshop/being/shining_eye.png"
import misc_deck_legendary_icon from "./assets/workshop/other/misc_deck_legendary.png"
import misc_deck_icon from "./assets/workshop/other/misc_deck.png"
import misc_deck_rare_icon from "./assets/workshop/other/misc_deck_rare.png"
import misc_crystal_icon from "./assets/workshop/rock/misc_crystal.png"
import gozag_0_icon from "./assets/workshop/artifacts/gozag_0.png"
import gozag_1_icon from "./assets/workshop/artifacts/gozag_1.png"
import gozag_2_icon from "./assets/workshop/artifacts/gozag_2.png"
import nemelex_1_icon from "./assets/workshop/artifacts/nemelex_1.png"
import nemelex_2_icon from "./assets/workshop/artifacts/nemelex_2.png"
import nemelex_3_icon from "./assets/workshop/artifacts/nemelex_3.png"
import nemelex_4_icon from "./assets/workshop/artifacts/nemelex_4.png"
import nemelex_5_icon from "./assets/workshop/artifacts/nemelex_5.png"
import qazlal_0_icon from "./assets/workshop/artifacts/qazlal_0.png"
import qazlal_1_icon from "./assets/workshop/artifacts/qazlal_1.png"
import qazlal_2_icon from "./assets/workshop/artifacts/qazlal_2.png"
import dithmenos_icon from "./assets/workshop/artifacts/dithmenos.png"
import dithmenos_2_icon from "./assets/workshop/artifacts/dithmenos_2.png"
import dithmenos_3_icon from "./assets/workshop/artifacts/dithmenos_3.png"
import vehumet_1_icon from "./assets/workshop/artifacts/vehumet_1.png"
import vehumet_2_icon from "./assets/workshop/artifacts/vehumet_2.png"
import misc_stone_icon from "./assets/workshop/rock/misc_stone.png"
import snapping_turtle_icon from "./assets/workshop/being/snapping_turtle.png"
import boulder_icon from "./assets/workshop/rock/boulder.png"
import statue_orb_icon from "./assets/workshop/artifacts/statue_orb.png"
import altar_cheibriados_icon from "./assets/workshop/artifacts/altar_cheibriados.png"
import skeleton_hydra_icon from "./assets/workshop/other/skeleton_hydra.png"
import statue_sword_icon from "./assets/workshop/artifacts/statue_sword.png"
import statue_hydra_icon from "./assets/workshop/artifacts/statue_hydra.png"
import statue_triangle_icon from "./assets/workshop/artifacts/statue_triangle.png"
import urand_high_council_icon from "./assets/workshop/clothes/urand_high_council.png"
import urand_pondering_icon from "./assets/workshop/clothes/urand_pondering.png"
import pink_icon from "./assets/workshop/potion/pink.png"
import misc_bottle_icon from "./assets/workshop/other/misc_bottle.png"
import urand_fencer_icon from "./assets/workshop/clothes/urand_fencer.png"
import gold_sparkles_1_icon from "./assets/workshop/elements/gold_sparkles_1.png"
import gold_sparkles_2_icon from "./assets/workshop/elements/gold_sparkles_2.png"
import gold_sparkles_3_icon from "./assets/workshop/elements/gold_sparkles_3.png"
import drain_0_new_icon from "./assets/workshop/elements/drain_0_new.png"
import drain_1_new_icon from "./assets/workshop/elements/drain_1_new.png"
import drain_2_new_icon from "./assets/workshop/elements/drain_2_new.png"
import irradiate_0_icon from "./assets/workshop/elements/irradiate_0.png"
import irradiate_1_icon from "./assets/workshop/elements/irradiate_1.png"
import irradiate_2_icon from "./assets/workshop/elements/irradiate_2.png"
import irradiate_3_icon from "./assets/workshop/elements/irradiate_3.png"
import flame_0_icon from "./assets/workshop/elements/flame_0.png"
import flame_1_icon from "./assets/workshop/elements/flame_1.png"
import flame_2_icon from "./assets/workshop/elements/flame_2.png"
import frost_0_icon from "./assets/workshop/elements/frost_0.png"
import frost_1_icon from "./assets/workshop/elements/frost_1.png"
import mirror_icon from "./assets/workshop/other/mirror.png"
import rune_gloorx_vloq_icon from "./assets/workshop/runes/rune_gloorx_vloq.png"
import rune_tomb_icon from "./assets/workshop/runes/rune_tomb.png"
import rune_cocytus_icon from "./assets/workshop/runes/rune_cocytus.png"
import rune_gehenna_icon from "./assets/workshop/runes/rune_gehenna.png"
import fulminant_prism_4_icon from "./assets/workshop/elements/fulminant_prism_4.png"
import misc_phantom_mirror_icon from "./assets/workshop/other/misc_phantom_mirror.png"
import magic_lamp_icon from "./assets/workshop/other/magic_lamp.png"
import simulacrum_hydra_5_icon from "./assets/workshop/artifacts/simulacrum_hydra_5.png"
import worldbinder_icon from "./assets/workshop/elements/worldbinder.png"
import wretched_star_icon from "./assets/workshop/elements/wretched_star.png"
import orb_of_electricity_icon from "./assets/workshop/elements/orb_of_electricity.png"
import orb_of_ice_icon from "./assets/workshop/elements/orb_of_ice.png"
import orb_of_fire_new_icon from "./assets/workshop/elements/orb_of_fire_new.png"
import maelstrom_1_icon from "./assets/workshop/elements/maelstrom_1.png"
import maelstrom_2_icon from "./assets/workshop/elements/maelstrom_2.png"
import maelstrom_3_icon from "./assets/workshop/elements/maelstrom_3.png"
import maelstrom_4_icon from "./assets/workshop/elements/maelstrom_4.png"
import orb_of_destruction_1_icon from "./assets/workshop/elements/orb_of_destruction_1.png"
import orb_of_destruction_2_icon from "./assets/workshop/elements/orb_of_destruction_2.png"
import fire_vortex_2_icon from "./assets/workshop/elements/fire_vortex_2.png"
import fire_vortex_3_icon from "./assets/workshop/elements/fire_vortex_3.png"
import fire_vortex_4_icon from "./assets/workshop/elements/fire_vortex_4.png"
import spatial_vortex_1_icon from "./assets/workshop/elements/spatial_vortex_1.png"
import spatial_vortex_2_icon from "./assets/workshop/elements/spatial_vortex_2.png"
import spatial_vortex_3_icon from "./assets/workshop/elements/spatial_vortex_3.png"
import spatial_vortex_4_icon from "./assets/workshop/elements/spatial_vortex_4.png"

const workshopItems:IWItem[] = [
    {
      id: 3,
      name: "Учебный посох",
      profit: 0,
      ctg: "guns",
      type: "magic",
      price: 15,
      icon: [staff_icon],
      max_level: 1,
      skill: 1,
      formula: [],
      description: "Этот корявый посох яркого красного цвета, словно огненная ветка из волшебного леса, хранит в себе тайны древней магии. Он пульсирует энергией, позволяя молодым магам наполнять мир чудесами. Верный спутник на пути обучения. Этот посох всегда готов поддержать юного волшебника, открывая двери к невероятным открытиям!",
    },
    {
      id: 1,
      name: "Нож",
      profit: 0,
      ctg: "guns",
      type: "plain",
      price: 100,
      icon: [knife_icon],
      max_level: 1,
      skill: 4,
      formula: [],
      description: "Этот исключительный нож, выкованный в недрах древнего леса, обрамлен переливающимися рунами, которые светятся в темноте. Его лезвие изготовлено из редкого металла, который не только остро, но и способно усиливать магию творца с каждым движением. Используя этот нож, любой рукотворный шедевр обретает душу и жизненную силу! Примените его в своих магических делах и откройте новые горизонты творчества!",
    },
    {
      id: 5,
      name: "Волшебная палочка",
      profit: 0.09,
      ctg: "guns",
      type: "magic",
      price: 150,
      icon: [wand_icon],
      max_level: 1,
      skill: 1,
      formula: [],
      description: "Скованные тайным волшебством, волшебная палочка шепчет заклинания, как дуновение ветра. Она может даровать мерцающие искры, сверкающие в темноте, а в руках истинного мага, облаченного в чары, способны возникнуть огненные видения. Лишь отважные ученики откроют её истинный потенциал, превращая мгновения в яркое волшебство.",
    },
    {
      id: 2,
      name: "Трость друида",
      profit: 0.8,
      ctg: "guns",
      type: "magic",
      price: 860.4,
      icon: [rod_icon],
      max_level: 1,
      skill: 6,
      formula: [],
      description: "Прикосновение к этой трости приводит к тому, что мир вокруг наполняется трепетом. Друид, держась за неё, может вызвать превращение безмолвных растений в чудовищных созданий, полных силы и дикой энергии. Каждое заклинание, произнесенное с помощью этой трости, вызывает шёпот ветра и звонкий смех лесных духов, а на земле расцветает магия, превращая мир в настоящий театр чудес.",
    },
    {
      id: 4,
      name: "Меч забытого ветра",
      profit: +8,
      ctg: "guns",
      type: "magic",
      price: 20000,
      icon: [sword_icon],
      skill: 4,
      max_level: 1,
      formula: [],
      description: "Затерянный в бескрайних просторах времени, Меч Забытого Ветра был найден среди руин древнего храма. Легенды гласят, что он однажды спас отважного героя, сразившегося с тёмным чудовищем. В его лезвии таится магия старинных бурь, и лишь тот, кто достоин, сможет пробудить его силу и повести свет к победе.",
    },
    {
      id: 95,
      name: "Статуя мудрости",
      profit: 276.131,
      ctg: "artifacts",
      type: "rare",
      price: 13400,
      icon: [altar_cheibriados_icon],
      skill: 4,
      max_level: 10,
      formula: [94, 1, 92],
      description: "Величественная скульптура древней черепахи из необработанного камня излучает магическую ауру, окутывая вокруг себя тихую мистику. Нежные линии и детали панциря рассказывают о вечности, а светлый зеленый мох, обвивающий её, придаёт ощущение жизни. Говорят, что она охраняет секреты времени, и каждый, кто прикоснётся, ощущает прилив мудрости и спокойствия.",
    },
    {
      id: 115,
      name: "Молниеносная призма",
      profit: 88.2,
      ctg: "artifacts",
      type: "rare",
      price: 18400,
      icon: [fulminant_prism_4_icon],
      skill: 5,
      max_level: 11,
      formula: [110, 111],
      description: "Загадочный артефакт, способный сосредоточивать энергию молний и преобразовывать её в мощные заклинания. При попадании света в призму, она искрится яркими цветами, отражая магическую силу.",
    },
    {
      id: 6,
      name: "Огонь Призрачной Руны",
      profit: 122.44,
      ctg: "artifacts",
      type: "magic",
      price: 25266,
      icon: [fire_icon],
      skill: 5,
      max_level: 6,
      formula: [21, 22],
      description: "В таинственной глубине сокрыт Огонь Призрачной Руны, извивающийся в неведомом сосуде. Этот редчайший огонь излучает ману, пробуждая потаённые силы. Лишь тем, кто постиг тайны, открываются его благословения. Он светит вечно, пока не решит угаснуть, шепча о забытой магии и невидимых узорах вечности.",
    },
    {
      id: 7,
      name: "Безмолвная сущность",
      profit: 13.7,
      ctg: "being",
      type: "rare",
      price: 990.7,
      icon: [acid_blob_icon],
      skill: 4,
      max_level: 17,
      formula: [2, 20],
      description: "Плод магии и таинства в тенях древнего леса. Его кислотные красные пупырышки мерцают, как следы старых бед, она ведет к темным мыслям и заброшенным мечтам. Эта сущность не раздумывает — она лишь прячется в тенях и наблюдает, как странники сталкиваются с собственными страхами, погружая их в бездну их же разочарований.",
    },
    {
      id: 92,
      name: "Мудрая черепаха",
      profit: 0,
      ctg: "being",
      type: "plain",
      price: 1550.6,
      icon: [snapping_turtle_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Старая черепаха, величественная и мудрая, медленно движется по берегу, оставляя за собой следы в песке. Её панцирь, покрытый морскими укладками, рассказывает о долгих годах, проведённых в океане. Она любит солнце, нежится под его теплом и наблюдает за жизнью вокруг. Каждый её взгляд наполнен историями, которые она хранит в своём сердце.",
    },
    {
      id: 8,
      name: "Волшебный колпак",
      profit: 0.9,
      ctg: "clothes",
      type: "magic",
      price: 250,
      icon: [cornuthaum_icon],
      skill: 1,
      max_level: 1,
      formula: [],
      description: "Волшебный колпак, украшенный звездами и луной, представляет собой незаменимый инструмент для магов-учеников. Этот волшебный атрибут является ключом к тайнам магии, позволяя каждому ученику создавать волшебство, погружаясь в мир неведомых знаний",
    },
    {
      id: 9,
      name: "Эфирная пыль",
      profit: 1.8,
      ctg: "elements",
      type: "magic",
      price: 49.895,
      icon: [cloud_calc_dust_1, cloud_calc_dust_2, cloud_calc_dust_3],
      max_level: 3,
      skill: 1,
      formula: [3],
      description: "Невидимая нить между мирами, переливающаяся белоснежными облачками. Она танцует в воздухе, создавая волшебный настрой для начинающих магов. Научитесь ловить её потоки, и она откроет перед вами врата неизведанных знаний, наполняя сердце уверенностью и вдохновением. ",
    },
    {
      id: 10,
      name: "Яблоко",
      profit: 0,
      ctg: "food",
      type: "plain",
      price: 14,
      icon: [apple_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Яркий плод с гладкой кожицей, который манит своим свежим ароматом. Его хрустящая текстура и сладковато-кислый вкус дарят удовольствие при каждом укусе. Наполненное витаминами и энергией, это яблоко идеально подходит для здоровья и отличного настроения, добавляя яркие ноты в каждый день.",
    },
    {
      id: 20,
      name: "Зеленый куст",
      profit: 0,
      ctg: "plants",
      type: "plain",
      price: 22,
      icon: [bush_icon],
      skill: 6,
      max_level: 1,
      formula: [],
      description: "Этот куст, обладая густой зелёной листвой и характерной формой, служит естественным элементом ландшафта. Его округлые очертания слегка напоминают барбарис, создавая уютные заросли, которые притягивают взгляды. Незатейливый и неприметный, куст гармонично вписывается в окружающую среду, обеспечивая укрытие для мелких существ и способствуя разнообразию флоры.",
    },
    {
      id: 19,
      name: "Папоротник",
      profit: 0,
      ctg: "plants",
      type: "plain",
      price: 89,
      icon: [briar_patch_icon],
      skill: 6,
      max_level: 1,
      formula: [],
      description: "Папоротник Псилот — это признак устойчивости и простоты природы. С его зелеными, тонкими побегами и характерными листьями, он прекрасно адаптируется к различным условиям среды. Этот вид излучает спокойствие, обрамляя ландшафты и сообщая об обилии жизни. Идеален для создания теней и естественной глубины в любых уголках леса.",
    },
    {
      id: 21,
      name: "Каменная Чаша",
      profit: 0,
      ctg: "rock",
      type: "plain",
      price: 128,
      icon: [misc_disc_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Эта круглая чаша, изготовленная из прочного камня, обладает выдающимися свойствами термостойкости. Неглубокая, но достаточно вместительная, она способна удерживать огонь, не поддаваясь разрушению. Идеально подходит для ритуалов и приготовления пищи, чаша служит надёжным инструментом в условиях дикой природы, объединяя функциональность и долговечность в каждом своем зёрнышке.",
    },
    {
      id: 91,
      name: "Базальт",
      profit: 0,
      ctg: "rock",
      type: "plain",
      price: 180,
      icon: [misc_stone_icon],
      max_level: 1,
      skill: 4,
      formula: [],
      description: "Уникальный материал для создания скульптур, который привлекает художников своей прочностью и устойчивостью. Его плотная текстура обеспечивает надежную поддержку, позволяя реализовать самые амбициозные идеи в камне. Элегантный и таинственный цвет базальта прекрасно подчеркивает каждую деталь финальной работы, создавая завораживающий контраст между природной красотой материала и искусством скульптора.",
    },
    {
      id: 93,
      name: "Валун",
      profit: 0,
      ctg: "rock",
      type: "plain",
      price: 500,
      icon: [boulder_icon],
      max_level: 1,
      skill: 4,
      formula: [],
      description: "Массивный древний валун, округлой формы и покрытый мохом, словно хранит в себе тайны веков. Его шершавая поверхность передает ощутимую связь с природой, а весомость напоминает о силе времени.",
    },
    {
      id: 94,
      name: "Круглый макет",
      profit: 0,
      ctg: "rock",
      type: "plain",
      price: 2000,
      icon: [statue_orb_icon],
      max_level: 1,
      skill: 4,
      formula: [91, 1, 93],
      description: "Круглая плита, выполненная из легкого бальзата, предназначена для мага-скульптора. Она словно портал в мир творчества, позволяя магической энергии сосредоточиться и проявиться в материале.",
    },
    {
      id: 15,
      name: "Магический постамент",
      profit: 2.8,
      ctg: "rock",
      type: "magic",
      price: 18860.4,
      icon: [altar_base_icon],
      max_level: 1,
      skill: 4,
      formula: [],
      description: "Творение из древних материалов, окутанное магией. При размещении на нем магического предмета, он превращается в священный алтарь, излучающий гармонию и энергию. Этот постамент способен усиливать силу артефактов, предоставляя защиту и вдохновение.",
    },
    {
      id: 111,
      name: "Руна мистики",
      profit: 5.59,
      ctg: "runes",
      type: "magic",
      price: 1400,
      icon: [rune_gloorx_vloq_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Элегантная темно-синяя руна излучает таинственную силу, соединяя глубину ночи с мистикой. Ее сияние притягивает внимание и наполняет пространство энергией магии и защиты. С её помощью можно раскрыть скрытые знания и обрести мудрость предков, проникая в мир необъяснимого и загадочного.",
    },
    {
      id: 16,
      name: "Руна стигматизма",
      profit: 7.9,
      ctg: "runes",
      type: "magic",
      price: 2000,
      icon: [rune_abyss_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Эта руна, вырезанная из тёмного камня красного цвета, пронизана энергией потустороннего мира. Её присутствие вызывает уважение и страх, напоминает о границах, которые не следует пересекать. Хранит секреты древних племён и ведёт к непростым истинам, доступным лишь тем, кто готов столкнуться с неизведанным.",
    },
    {
      id: 17,
      name: "Живая Вода",
      profit: 0,
      ctg: "potion",
      type: "plain",
      price: 24,
      icon: [sky_blue_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Эта неприметная вода, извлеченная из кристально чистых источников, обладает способностью объединять различные компоненты. Используя её в своих зельях, алхимики получают возможность создавать уникальные смеси. Хотя сама вода не содержит магии, её питательные свойства помогают раскрывать потенциал редких ингредиентов, превращая обычные рецепты в настоящие шедевры.",
    },
    {
      id: 102,
      name: "Тропический нектар",
      profit: 3.76,
      ctg: "potion",
      type: "magic",
      price: 780,
      icon: [pink_icon],
      max_level: 5,
      skill: 1,
      formula: [],
      description: "В кристаллической колбе сверкает розовая жидкость — нектар экзотического цветка, собранного в тропических джунглях. Его сладкий, нежный аромат окутывает словно легкий шелк, пробуждая воспоминания о жарких летних днях.",
    },
    {
      id: 65,
      name: "Кислота",
      profit: 0,
      ctg: "potion",
      type: "plain",
      price: 912,
      icon: [potion_bubbly_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Химическое вещество, обладающее способностью отдавать протоны (ион водорода) в растворе, часто используемое в лабораторных экспериментах для реакции с основаниями и других химических процессов.",
    },
    {
      id: 64,
      name: "Колба жизни",
      profit: 2.9,
      ctg: "potion",
      type: "magic",
      price: 11830,
      icon: [bubbly_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Необычное вещество, обладающее способностью оживлять неодушевленные предметы. При взаимодействии с материалами, жидкость запускает процесс их преобразования, позволяя объектам обрести сознание и индивидуальность. Используется в научных экспериментах и магических ритуалах. Требует осторожного обращения из-за непредсказуемых результатов.",
    },
    {
      id: 13,
      name: "Эссенция Левитации",
      profit: 3.3,
      ctg: "potion",
      type: "magic",
      price: 13100,
      icon: [white_potion_icon],
      max_level: 4,
      formula: [],
      skill: 7,
      description: "В колбе сохранена прозрачная жидкость с легким перламутровым отливом. Эссенция Левитации обладает уникальной способностью придавать предметам невесомость. При капле на поверхность, она вызывает эффект парения, открывая новые возможности для исследователей. Легкий аромат подчеркивает её магические свойства, делая каждый эксперимент восхитительным открытием.",
    },
    {
      id: 14,
      name: "Нектар бездны",
      profit: 11.3,
      ctg: "potion",
      type: "magic",
      price: 14000,
      icon: [black_potion_icon],
      max_level: 3,
      skill: 7,
      formula: [17, 11, 13],
      description: "В колбе содержится таинственная жидкость - смесь левитации и древности. Этот темный эликсир не только позволяет предметам левитировать, но также усиливает силу магии, пробуждает скрытые силы, позволяя манипулировать тенями и влиять на разум. Идеален для опытных алхимиков и искателей приключений.",
    },
    {
      id: 22,
      name: "Руна призрачного огня",
      profit: 14.4,
      ctg: "runes",
      type: "magic",
      price: 2800,
      icon: [rune_cerebov_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "В глубинах Руна Призрачного Огня таит в себе редкий огонь, плетущий нити манны и пробуждающий скрытые силы. Лишь тем, кто изучает древние тайны, открываются её благословения. Эта руна светит вечно, шепча о забытой магии и невидимых узорах вечности, представляя собой ключ к новым возможностям и трансформациям.",
    },

    {
      id: 110,
      name: "Зеркало",
      profit: 0.00001,
      ctg: "other",
      type: "plain",
      price: 200,
      icon: [mirror_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Элегантное зеркальце с деревянной ручкой сочетает в себе стиль и функциональность. Изготовлено из высококачественных материалов, оно отличается прочной конструкцией и приятной на ощупь текстурой. Идеально подходит для ежедневного использования или в качестве стильного аксессуара.",
    },
    {
      id: 24,
      name: "Ключ от сундука",
      profit: 0,
      ctg: "other",
      type: "plain",
      price: 500,
      icon: [key_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Загадочный ключ, который открывает доступ к сундуку. Тонкая работа мастера придаёт ему величественный вид, а его магические свойства гарантируют, что только истинный искатель сможет раскрыть тайны, скрытые внутри. Используйте его с осторожностью, ведь за каждым сокровищем скрыты свои испытания.",
    },
    {
      id: 23,
      name: "Сундук",
      profit: 0,
      ctg: "other",
      type: "plain",
      price: 1000,
      icon: [chest_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Неброский сундук, покрытый пылью времён, который скрывает в своих недрах редкие артефакты и древние знания. Открывая его, авантюристы могут обнаружить драгоценности, уникальные аксессуары и магические книги, способные изменить ход событий. Сундук служит напоминанием о том, что сокровища древности ждут тех, кто осмелится искать их среди теней прошлого.",
    },
    {
      id: 103,
      name: "Волшебная колба",
      profit: 7.8,
      ctg: "other",
      type: "magic",
      price: 1200,
      icon: [misc_bottle_icon],
      max_level: 2,
      formula: [],
      skill: 1,
      description: "В тени древнего леса спрятана синяя глиняная колба, переливающаяся загадочным светом. Её поверхность украшена таинственными узорами, словно шепчущими забытые секреты. Только тот, кто искренне верит в магию, сможет раскрыть её тайну и воспользоваться могуществом, запертым в этом чуде.",
    },

    {
      id: 18,
      name: "Горн силы",
      profit: 1.7,
      ctg: "other",
      type: "magic",
      price: 1560.63,
      icon: [misc_horn_icon],
      max_level: 1,
      skill: 6,
      formula: [],
      description: "Этот изысканный горн цвета кости таит в себе тайны магии. Украсивший его загадочный узор словно шепчет о древних силах, пробуждая в сердце слушателя непреодолимое стремление к открытиям. При звуке горна вокруг струится неведомая энергия, способная привлекать внимание таинственных сущностей и открывать горизонты неизведанного.",
    },
    {
      id: 11,
      name: "Кости забытого зверя",
      profit: 0,
      ctg: "other",
      type: "plain",
      price: 2440,
      icon: [bone_icon],
      max_level: 1,
      skill: 6,
      formula: [],
      description: "В самом сердце волшебного леса таятся загадочные кости, оставшиеся от создания, что скользило по теням. Эти артефакты хранят древнюю магию, вплетенную в ткани времени. Они ждут смелого искателя, готового раскрыть тайны, сокрытые в их холодной белизне, и пробудить забытую силу сказаний.",
    },
    {
      id: 116,
      name: "Призрачное зеркало",
      profit: 12.314,
      ctg: "other",
      type: "magic",
      price: 5266,
      icon: [misc_phantom_mirror_icon],
      max_level: 2,
      skill: 5,
      formula: [110, 16],
      description: "В полумраке заброшенного замка стоит магическое призрачное зеркало с красным корпусом, окутанное легкой вуалью тумана. Его осколки отражают не только образы, но и заклинания забытых душ. Легенды гласят, что глядя в него, можно услышать шепот прошлого, но только самый смелый сможет вынести его тайны",
    },
    {
      id: 25,
      name: "Свиток физики",
      profit: 0,
      ctg: "chest",
      type: "magic",
      price: 0,
      icon: [scroll_purple_icon],
      max_level: 1,
      skill: 2,
      formula: [],
      description: "Содержимое свитка содержит секреты древних электрических магий, которые раскрывают способы управления ударами молний.",
    },
    {
      id: 26,
      name: "Свиток огня",
      profit: 0,
      ctg: "chest",
      type: "magic",
      price: 0,
      icon: [scroll_yellow_icon],
      max_level: 1,
      skill: 2,
      formula: [],
      description: "Свиток содержит заклинание, позволяющее создать сферу огня, которая мгновенно разжигает и сжигает все на своем пути. Арканисту следует пристально изучить содержимое, чтобы избежать непредвиденных последствий при использовании мощного огненного заклинания.",
    },
    {
      id: 27,
      name: "Свиток мерзлоты",
      profit: 0,
      ctg: "chest",
      type: "magic",
      price: 0,
      icon: [scroll_blue_icon],
      max_level: 1,
      skill: 2,
      formula: [],
      description: "Внутри свитка заключена информация о древних ледяных заклинаниях, передаваемая из поколения в поколение.",
    },
    {
      id: 28,
      name: "Свиток потока",
      profit: 0,
      ctg: "chest",
      type: "magic",
      price: 0,
      icon: [scroll_cyan_icon],
      max_level: 1,
      skill: 2,
      formula: [],
      description: "Свиток содержит древние знания о создании магического водоворота, способного поглотить все вокруг. Активируя свиток, элементалист вызывает морскую стихию, используя силы воды. Однако содержание требует глубокого понимания магии, чтобы контролировать мощный поток.",
    },
    {
      id: 29,
      name: "Свиток разрушения",
      profit: 0,
      ctg: "chest",
      type: "magic",
      price: 0,
      icon: [scroll_red_icon],
      max_level: 1,
      skill: 2,
      formula: [],
      description: "Свиток хранит в себе мощь разрушительных заклинаний, позволяя элементалисту создать сферу разрушения. Открывая свиток, заклинатель чувствует гулкую силу, способную уничтожать преграды и врагов на своем пути. Содержимое свитка требует осторожности, чтобы не развязать хаос.",
    },
    {
      id: 30,
      name: "Пергамент судьбы",
      profit: 1.96,
      ctg: "chest",
      type: "majestic",
      price: 22.6,
      icon: [scroll_epic_icon],
      max_level: 4,
      skill: 2,
      formula: [],
      description: "Содержание свитка может поразить обычного мага. Он содержит древние заклинания, способные изменить реальность. Даже обыденный человек не сможет предугадать его истинную мощь!",
    },
    {
      id: 31,
      name: "Сердце феникса",
      profit: 0.03,
      ctg: "chest",
      type: "magic",
      price: 0.66,
      icon: [celtic_red_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Красный амулет из магического пера защищает от невзгод и способствует обновлению. Он помогает восстанавливать силы после трудных испытаний, позволяя переродиться духовно и преодолевать любые препятствия на пути к предназначению.",
    },
    {
      id: 32,
      name: "Кольцо древности",
      profit: 0.04,
      ctg: "chest",
      type: "magic",
      price: 0.51,
      icon: [urand_shadows_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Кольцо с загадочными символами древних магий обладает уникальной силой. Оно усиливает магические способности владельца и открывает доступ к древним знаниям. Гравировка активирует интуицию и помогает распознавать скрытые знаки судьбы.",
    },
    {
      id: 33,
      name: "Подвеска силы",
      profit: 0.04,
      ctg: "chest",
      type: "magic",
      price: 0.48,
      icon: [stone_2_blue_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Синий кристалл в серебряной оправе становится источником бесконечной энергии. Он обостряет интуицию и помогает принимать мудрые решения, раскрывая скрытый потенциал владельца. Носитель ощущает прилив силы и уверенности в своих действиях.",
    },
    {
      id: 34,
      name: "Золотое кольцо",
      profit: 0.05,
      ctg: "chest",
      type: "magic",
      price: 0.63,
      icon: [gold_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Золотое кольцо, инкрустированное цитрином, излучает ауру богатства и успеха. Его магия наполняет жизнь владельца радостью и благополучием. Это кольцо помогает привлечь удачу в финансовых делах и развивает творческий потенциал, поднимая настроение и вдохновляя на новые свершения.",
    },
    {
      id: 35,
      name: "Ожерелье любви",
      profit: 1.6,
      ctg: "chest",
      type: "rare",
      price: 4.9,
      icon: [stone_3_magenta_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Драгоценный амулет, который привлекает любовь и восстанавливает стертую магию чувств. Он наполнен заклинаниями, которые бушуют в сердцах, и разжигают пламя в отношениях, даруя им совершенство и гармонию.",
    },
    {
      id: 36,
      name: "Земное кольцо",
      profit: 2.24,
      ctg: "chest",
      type: "rare",
      price: 6.4,
      icon: [bronze_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Бронзовое кольцо содержит в себе магию земли, дарящую владельцу защиту и стабильность. Его энергия помогает обрести мудрость и ясность в принятии решений. Этот амулет углубляет связь с природой, даря силу и уверенность при столкновении с трудностями, что делает его идеальным спутником для реалистов и практиков.",
    },
    {
      id: 37,
      name: "Медальон метеор",
      profit: 2.92,
      ctg: "chest",
      type: "rare",
      price: 7,
      icon: [bone_gray_icon],
      max_level: 10,
      skill: 0,
      formula: [],
      description: "Сделанный из упавшего метеорита, этот амулет наполняет владельца энергией космоса. Он пробуждает вдохновение и дарует удачу, открывая новые возможности и предотвращая неудачи. Обладатель начинает чувствовать связь с древними знаниями, которые могут изменить его судьбу.",
    },
    {
      id: 38,
      name: "Кольцо природы",
      profit: 1.35,
      ctg: "chest",
      type: "rare",
      price: 0.56,
      icon: [emerald_icon],
      max_level: 15,
      skill: 0,
      formula: [],
      description: "Изумрудное кольцо наполнено целебной магией, способствующей восстановлению здоровья и внутренней гармонии. Этот камень укрепляет связи с природой, дарит покой и умиротворение. Владельцу открываются новые возможности для роста и развития, что делает кольцо идеальным для искателей гармонии в жизни и исцеления от душевных ран.",
    },
    {
      id: 39,
      name: "Печатка любви",
      profit: 8.5,
      ctg: "chest",
      type: "precious",
      price: 13.4,
      icon: [ruby_icon],
      max_level: 15,
      skill: 0,
      formula: [],
      description: "Рубиновое кольцо излучает энергию любви и стремления к успеху. Оно пробуждает в человеке уверенность и харизму, привлекает удачу в любовных делах и бизнесе. Владельцы этого кольца отмечают улучшение отношений и общую атмосферу счастья в жизни. Это кольцо становится не только украшением, но и важным магическим амулетом.",
    },
    {
      id: 40,
      name: "Кулон ночи",
      profit: 14.8,
      ctg: "chest",
      type: "precious",
      price: 15.9,
      icon: [urand_air_icon],
      max_level: 8,
      skill: 0,
      formula: [],
      description: "Амулет, который вызывает магию ночи и открывает двери в мир фантазий. Носитель обретает способности летать между мирами, превращая обыденность в волшебство. Этот амулет шепчет древние заклинания, даруя вдохновение и превращая желания в реальность.",
    },
    {
      id: 41,
      name: "Талисман из яшмы",
      profit: 16.1,
      ctg: "chest",
      type: "precious",
      price: 17.1,
      icon: [urand_bloodlust_icon],
      max_level: 6,
      skill: 0,
      formula: [],
      description: "Амулет из яшмы, инкрустированный знаками силы, оберегает от негативных энергий. Его теплая текстура и яркие оттенки приносят спокойствие и защищают от зависти. Искатели света могут найти в нем ключ к внутреннему гармонии и благополучию.",
    },
    {
      id: 42,
      name: "Лимб вулкана",
      profit: 9.8,
      ctg: "chest",
      type: "precious",
      price: 16,
      icon: [urand_octoring_icon],
      max_level: 18,
      skill: 0,
      formula: [],
      description: "Искусно выкованное из самого сердца вулкана, это кольцо является символом непокоримости. Оно разжигает в своем хозяине огонь неугасимой решимости, позволяя преодолевать любые преграды. Каждый его взгляд словно веское решение, способное сколыхнуть мир. Враги трепещут, сталкиваясь с пламенем его воли.",
    },
    {
      id: 43,
      name: "Тень непокорности",
      profit: 21.9,
      ctg: "chest",
      type: "precious",
      price: 50.6,
      icon: [ring_black_onyx_icon],
      max_level: 13,
      skill: 0,
      formula: [],
      description: "Невероятное кольцо, скрывающее в себе силу древних божеств. Оно окутывает своего владельца непроницаемой броней тьмы, отражая любую магию и защищая от зла. Когда враги смотрят на его владельца, они видят не человека, а могучую тень, готовую поглотить их страхи и слабости.",
    },
    {
      id: 44,
      name: "Лунный кристалл",
      profit: 38.4,
      ctg: "chest",
      type: "majestic",
      price: 60.6,
      icon: [urand_vitality_icon],
      max_level: 18,
      skill: 0,
      formula: [],
      description: "Амулет излучающий мягкий свет. Он хранит силу ночи и помогает развивать интуицию. Обладателю даруются мечты, предвещающие грядущие события. Старейшины говорили, что лишь сердцу чистому открываются тайны лунных небес.",
    },
    {
      id: 45,
      name: "Перстень бесконечности",
      profit: 45.9,
      ctg: "chest",
      type: "majestic",
      price: 50.6,
      icon: [steel_icon],
      max_level: 39,
      skill: 0,
      formula: [],
      description: "Это кольцо, выкованное в недрах забытого мира, пронизано тенями древних секретов. Его носитель обретает способность предвидеть события, управляя судьбами. Зрительные образы проходят сквозь время, словно туман, а каждая мысль излучает силу, способную сокрушить самых сильнейших .",
    },
    {
      id: 46,
      name: "Всевидящее Око",
      profit: 66.6,
      ctg: "chest",
      type: "majestic",
      price: 120.3,
      icon: [eye_magenta_icon],
      max_level: 22,
      skill: 0,
      formula: [],
      description: "Позолоченный треугольный амулет с живым глазом в центре. Этот магический артефакт обладает мощной силой, позволяющей видеть правду за иллюзиями. Он усиливает интуицию и дарует владельцу защиту от тёмных сил. Считается, что только истинно чистые сердцем могут полностью раскрыть его потенциал. Энергия амулета становится активной при благих намерениях.",
    },
    {
      id: 47,
      name: "Секреты луны",
      profit: 404.2,
      ctg: "chest",
      type: "precious",
      price: 800.3,
      icon: [glittering_icon],
      max_level: 2,
      skill: 0,
      formula: [],
      description: "Древняя магическая книга, покрытая искрящимся блеском. Она содержит древние знания о магии и манипуляциях временем. Легенда гласит, что любой, кто попытается открыть её, будет вынужден столкнуться с иллюзиями, отражающими его истинные намерения. Лишь истинный маг сумеет понять её сложные тайны и избежать искушений.",
    },
    {
      id: 48,
      name: "Книга некроманта",
      profit: 333.3,
      ctg: "chest",
      type: "precious",
      price: 800.3,
      icon: [book_of_the_dead_icon],
      max_level: 4,
      skill: 0,
      formula: [],
      description: "Черное издание с жутким содержанием. Говорят, что это древний гримуар, погруженный в темные заклятия. Каждый, кто открыл его, навлекал на себя гнев мертвых, вызывая души, жаждущие мести. Легенда предупреждает: страницы книги пропитаны кровью магов, когда-либо осмелившихся проникнуть в тайны жизни и смерти.",
    },
    {
      id: 49,
      name: "Книга пламенных тайн",
      profit: 637,
      ctg: "chest",
      type: "majestic",
      price: 1100.54,
      icon: [misc_book_icon],
      max_level: 4,
      skill: 0,
      formula: [],
      description: "В сердце древнего леса лежит загадочная книга, излучающая мощную магическую энергию. Никто не способен расшифровать её таинственный текст, написанный на исчезнувшем языке. Легенды гласят, что в её страницах скрыты секреты вселенной, способные изменить судьбу мира. Тот, кто осмелится открыть книгу, рискует сломать грань между реальностью и магией!",
    },
    {
      id: 50,
      name: "Учебник алхимика",
      profit: 0,
      ctg: "chest",
      type: "majestic",
      price: 0,
      icon: [buckle_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Книга для обучения магов-алхимиков погружает читателя в захватывающий мир алхимии — древнего искусства трансформации веществ и поиска философского камня. В ней рассматриваются основные принципы и теории алхимии, такие как трансмутация, символизм и свойства материалов.",
    },
    {
      id: 51,
      name: "Учебник друида",
      profit: 0,
      ctg: "chest",
      type: "majestic",
      price: 0,
      icon: [velvet_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Путеводитель по искусству друидизма, сосредоточенный на связи с природой и духовными практиками. В ней описываются основные принципы, философия и обряды, которые помогают углубить понимание природы и её стихий. Читатель найдёт информацию о траволечении, растительной магии, циклах природы и ритуалах, направленных на гармонию с окружающим миром. Книга также содержит практические упражнения и медитации для развития интуиции и силы духа.",
    },
    {
      id: 52,
      name: "Учебник чародея",
      profit: 0,
      ctg: "chest",
      type: "majestic",
      price: 0,
      icon: [copper_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Книга рассказывает о магии и чародейских практиках. В ней описаны различные виды заклинаний, ритуалов и техники, связанные с управлением магическими силами. Читатель найдёт подробные инструкции и объяснения, а также примеры использования магии в повседневной жизни. Книга затрагивает темы, такие как источники силы, медитация и взаимодействие с магическими существами.",
    },
    {
      id: 53,
      name: "Учебник мага-скульптора",
      profit: 0,
      ctg: "chest",
      type: "majestic",
      price: 0,
      icon: [white_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Книга предназначена для тех, кто хочет освоить искусство магической скульптуры. В ней описаны техники, позволяющие придавать форму магическим материалам и воплощать идеи в материю. Читатели узнают о различных инструментах, особенностях работы с энергией и способах создания оживленных произведений искусства. Пошаговые руководства и вдохновение для творчества помогут магу-скульптору раскрыть свой потенциал и создавать уникальные произведения.",
    },
    {
      id: 54,
      name: "Учебник заклинателя",
      profit: 0,
      ctg: "chest",
      type: "majestic",
      price: 0,
      icon: [bookmark_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Руководство по искусству заклинания, которое раскрывает секреты создания и использования магических заклинаний. Она охватывает различные типы заклинаний, их воздействия и способы управления магической энергией. Читатели найдут описание ритуалов, необходимых ингредиентов и советов по практике заклинаний, что позволит им развить свои навыки и понимание магии.",
    },
    {
      id: 55,
      name: "Учебник элементалиста",
      profit: 0,
      ctg: "chest",
      type: "myth",
      price: 0,
      icon: [plaid_icon],
      max_level: 1,
      skill: 0,
      formula: [],
      description: "Книга предлагает глубокое погружение в искусство элементализма, обучая читателя управлять четырьмя основными стихиями: огнём, водой, воздухом и землёй. В ней изложены основные принципы, техники и ритуалы, необходимые для становления элементалистом. Читатели найдут подробные инструкции для практики и экспериментов с энергиями природы.",
    },
    {
      id: 56,
      name: "Руна свободы",
      profit: 1217.2,
      ctg: "chest",
      type: "myth",
      price: 2002.7,
      icon: [generic_icon],
      max_level: 4,
      skill: 5,
      formula: [],
      description: "Эта руна — настоящее сокровище среди реликвий, попадающее в руки лишь счастливым искателям приключений. Она дарует обладателю невероятные силы и открывает доступ к уникальным умениям, недоступным остальным. Этот символ истинного мастерства освещает путь к величию, привнося гармонию и баланс в каждое сражение. Обретите её и станьте легендой!",
    },
    {
      id: 57,
      name: "Безмерный завет",
      profit: 8.42,
      ctg: "chest",
      type: "myth",
      price: 44.1,
      icon: [manual_1_icon],
      max_level: 2,
      skill: 4,
      formula: [],
      description: "Редчайший мануал, сияющий аурой загадки, предназначен для магов-скульпторов. Обладая его секретами, они могут создать треугольник Пенроуза — уникальную скульптуру, которая нарушает законы восприятия и дарует бесконечную силу. Каждый взгляд на неё пробуждает магию, превращая маны в неиссякаемый поток, недоступный иным.",
    },
    {
      id: 58,
      name: "Манускрипт бога",
      profit: 8.42,
      ctg: "chest",
      type: "myth",
      price: 44.2,
      icon: [manual_2_icon],
      max_level: 2,
      skill: 3,
      formula: [],
      description: "Могущественный мануал, вырезанный из древнего камня, который обладает огромной силой и энергией. Каждый иероглиф на его поверхности хранит в себе тайны времени и пространства, позволяя заклинателю открыть доступ к могуществу, недоступному обычным магам. Алтарь, основанный на его знаниях, станет основой для величайших заклинаний.",
    },
    {
      id: 59,
      name: "Апельсин",
      profit: 0,
      ctg: "food",
      type: "plain",
      price: 15,
      icon: [orange_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Яркий, сочный фрукт с насыщенным сладко-кислым вкусом. Его ярко-оранжевая кожура содержит много витамина C и полезных антиоксидантов.",
    },
    {
      id: 62,
      name: "Лимон",
      profit: 0,
      ctg: "food",
      type: "plain",
      price: 23,
      icon: [lemon_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Кислый цитрусовый фрукт с яркой желтой кожурой и сочной, кислой мякотью.",
    },
    {
      id: 63,
      name: "Пицца",
      profit: 0,
      ctg: "food",
      type: "plain",
      price: 39,
      icon: [pizza_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Круглый пирог из тонкого теста, покрытый томатным соусом и сыром, с разнообразными начинками, такими как мясо, овощи и специи, запеченный до золотистой корочки",
    },
    {
      id: 60,
      name: "Брынза",
      profit: 0,
      ctg: "food",
      type: "plain",
      price: 240,
      icon: [cheese_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Мягкий соленый сыр с кремовой текстурой и характерным вкусом, приготовленный из козьего молока.",
    },
    {
      id: 61,
      name: "Кусок мяса",
      profit: 0,
      ctg: "food",
      type: "plain",
      price: 560.5,
      icon: [chunk_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Кусок мяса, имеющий мясистую текстуру и равномерный цвет. Имеет небольшую мраморность, что придаёт ему сочность. Подходит для приготовления на гриле, варки или запекания",
    },
    {
      id: 66,
      name: "Кровь мегалодона",
      profit: 1.7,
      ctg: "potion",
      type: "magic",
      price: 23700,
      icon: [puce_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "Мегалодон - древний хищник, обитавший в океанах миллионы лет назад. Эта кровь имеет интенсивный красный цвет и обладает уникальными свойствами, которые могли бы быть исследованы для различных целей.",
    },
    {
      id: 67,
      name: "Кровь трехглавого",
      profit: 19.7,
      ctg: "potion",
      type: "magic",
      price: 70530,
      icon: [ruby_potion_icon],
      max_level: 1,
      skill: 7,
      formula: [],
      description: "В колбе находится кровь трехглавого дракона — мифического существа, олицетворяющего силу и разрушение. Эта густая красная жидкость содержит уникальные биоактивные компоненты, способствующие увеличению физической мощи и магической устойчивости.",
    },
    {
      id: 68,
      name: "Суп дракона",
      profit: 29.34,
      ctg: "food",
      type: "rare",
      price: 2000,
      icon: [stonesoup_icon],
      max_level: 12,
      skill: 7,
      formula: [17, 67, 61, 10, 62],
      description: "Густой бульон с кусочками мяса, освежённый яблоком и лимоном. Его уникальный состав наделяет блюдо магической силой, способной усиливать физическую и умственную стойкость.",
    },
    {
      id: 69,
      name: "Сырный сгусток",
      profit: 16.7,
      ctg: "being",
      type: "rare",
      price: 8800,
      icon: [starcursed_mass_icon],
      max_level: 7,
      skill: 7,
      formula: [60, 64, 13],
      description: "Прозрачный живой сгусток, обладающий сознанием и способностью левитации. Не имеет органов чувств, дышит спорами и взаимодействует с миром через вибрации.",
    },
    {
      id: 70,
      name: "Несчастный монстр",
      profit: 23.1,
      ctg: "being",
      type: "rare",
      price: 12250,
      icon: [chaos_spawn_icon],
      max_level: 9,
      skill: 7,
      formula: [13, 66, 67, 11],
      description: "Одноглазый хранитель знаний с костями древнего монстра и кровью дракона. Оно левитирует на щупальцах, обладает сверхчувствительным зрением и способно ускользать от врагов.",
    },
    {
      id: 71,
      name: "Зловещий тенет",
      profit: 73.11,
      ctg: "being",
      type: "rare",
      price: 18700,
      icon: [macabre_mass_icon],
      max_level: 6,
      skill: 7,
      formula: [64, 67, 63],
      description: "Абоминальное существо, возникшее в результате эксперементов. Оно имеет форму изогнутой, тянущейся вверх руки, стремящейся вырваться из своего зловещего гнезда. Тенет излучает споры, способные вызывать жуткие галлюцинации, а при вдохе всасывает кровь, оставляя лишь сухие лоскуты плоти.",
    },
    {
      id: 81,
      name: "Мертвый глаз",
      profit: 321.6,
      ctg: "being",
      type: "precious",
      price: 35500,
      icon: [shining_eye_icon],
      max_level: 12,
      skill: 6,
      formula: [75, 18, 2, 78],
      description: "Розовый детеныш, порождение темных сил друида, представляет собой омерзительное чудо. Его щупальца, обвитые ядовито-фиолетовыми полосами, корчатся в танце гипноза, а радужное свечение всегда манит жертв. В центре — зловещий красный зрачок, животного взгляда, что вызывает страх.",
    },
    {
      id: 72,
      name: "Кислотный выродок",
      profit: 151.7,
      ctg: "being",
      type: "rare",
      price: 90000,
      icon: [tentacled_monstrosity_icon],
      max_level: 7,
      skill: 7,
      formula: [59, 64, 65],
      description: "Существо из апельсина и химической кислоты внешне напоминает жирное зеленое образование с щупальцами и пятью маленькими глазами. Его кислотный цвет отражает токсичность, а щупальца безупречно маневрируют, подчеркивая его природу хищника в среде химических веществ.",
    },
    {
      id: 73,
      name: "Цитроарх",
      profit: 213.9,
      ctg: "being",
      type: "rare",
      price: 130000,
      icon: [chaos_spawn_4_icon],
      max_level: 17,
      skill: 7,
      formula: [13, 59, 64],
      description: "Магическое существо, сделанное из апельсина, представляет собой ромб с одиноким глазом и двумя зрачками. Оно левитирует, а вокруг него кружат маленькие круглые части, подобные пузырям, которыми оно защищается впрыскивая эти пузыри во врага.",
    },
    {
      id: 74,
      name: "Теневод",
      profit: 724.20,
      ctg: "being",
      type: "rare",
      price: 380000,
      icon: [chaos_spawn_3_icon],
      max_level: 14,
      skill: 7,
      formula: [64, 14],
      description: "Представляет собой круглую форму с беззрачным глазом. Оно не видит, но ощущает магическую энергию вокруг. Способность манипулировать тенями позволяет ему создавать иллюзии и скрывать истинные намерения.",
    },
    {
      id: 76,
      name: "Шип лотуса",
      profit: 0,
      ctg: "plants",
      type: "plain",
      price: 150,
      icon: [thorn_lotus_icon],
      max_level: 1,
      skill: 6,
      formula: [],
      description: "Уникальное растение, символизирующее чистоту и восхождение к свету. С его эффектными цветами и нежной текстурой, он воплощает гармонию природы и стиля.",
    },
    {
      id: 77,
      name: "Цветущий рипсалис",
      profit: 0,
      ctg: "plants",
      type: "plain",
      price: 380,
      icon: [plant_icon],
      max_level: 1,
      skill: 6,
      formula: [],
      description: "Представляет собой элегантное растение с листьями, которые могут иметь разнообразные оттенки зеленого. В период цветения на стеблях появляются небольшие, но выразительные цветы, чаще всего белого, желтого или розового цвета.",
    },
    {
      id: 78,
      name: "Вьющееся роза",
      profit: 0,
      ctg: "plants",
      type: "plain",
      price: 770,
      icon: [thorn_hunter_icon],
      max_level: 1,
      skill: 6,
      formula: [],
      description: "Вьющаяся роза представляет собой ценное дополнение садового искусства. Ее длинные побеги обвивают опоры, формируя изящные арки.",
    },
    {
      id: 79,
      name: "Гриб лотоса",
      profit: 15.9,
      ctg: "plants",
      type: "rare",
      price: 1186.3,
      icon: [giant_spore_icon],
      max_level: 13,
      skill: 6,
      formula: [2 , 76],
      description: "Гриб, созданный друидом из шипа лотоса с помощью магических заклинаний, представляет собой шарообразную спора ярко-желтого цвета. Его поверхность напоминает текстуру натурального материала. Этот организм обладает уникальными свойствами, позволяя ему адаптироваться к различным условиям окружающей среды.",
    },
    {
      id: 12,
      name: "Лазурное эхо",
      profit: 43.7,
      ctg: "plants",
      type: "rare",
      price: 1799.11,
      icon: [azure_icon],
      max_level: 9,
      skill: 6,
      formula: [18, 19],
      description: "Это загадочное создание представляет собой сгусток нежной бирюзы, который скрывает древние тайны природы. Его форма манит исследователей, отражая глубину времени. Каждый поворот света раскрывает новые оттенки его истинной сущности.",
    },
    {
      id: 80,
      name: "Зловещий рипсалис",
      profit: 243.7,
      ctg: "plants",
      type: "precious",
      price: 19592.2,
      icon: [plant_demonic_icon],
      max_level: 9,
      skill: 6,
      formula: [75, 18, 77],
      description: "Порождение тьмы, врос в землю, как насмешка над живыми. Его ядовитый фиолетовый цвет манит, словно зловещий свет в ночи, притягивая жертвы к гибели. Листья, как острые когти, готовы поглотить любого, кто осмелится приблизиться. Ужасное растение шепчет притяжение смерти, погружая мир в чёрную бездну.",
    },
    {
      id: 82,
      name: "Карты дракона",
      profit: 11.3,
      ctg: "other",
      type: "rare",
      price: 11700,
      icon: [misc_deck_legendary_icon],
      max_level: 1,
      skill: 3,
      formula: [],
      description: "Магические карты дракона созданы из древних материалов, отражающих силу и мудрость мифических существ. Каждая карта изображает уникального дракона, обладающего особыми способностями. При соприкосновении с магическим постаментом карты активируют скрытые силы, вызывая яркий золотой кристалл, наполняющий пространство магической энергией.",
    },
    {
      id: 83,
      name: "Карты знаний",
      profit: 11.6,
      ctg: "other",
      type: "rare",
      price: 11700,
      icon: [misc_deck_icon],
      max_level: 1,
      skill: 3,
      formula: [],
      description: "Карты изготовлены из редких материалов, содержащих древнюю мудрость. Каждая карта раскрывает уникальное знание, скилл или аспект мудрости, запечатлённый на ней. При соприкосновении с магическим постаментом карты активируют необычные силы, создавая алтарь, который наделяет человека мгновенными знаниями, открывающими новые горизонты ума.",
    },
    {
      id: 84,
      name: "Карты тьмы",
      profit: 11.9,
      ctg: "other",
      type: "rare",
      price: 11700,
      icon: [misc_deck_rare_icon],
      max_level: 1,
      skill: 3,
      formula: [],
      description: "Карты тьмы, созданные из редких материалов, переносят энергию бурь и стихии. Каждая карта изображает уникальный физический элемент.  При активации на магическом постаменте карты порождают алтарь, который создает мощную электрическую энергию, наполняя пространство вихрем электрической силы.",
    },
    {
      id: 75,
      name: "Молитвы друида",
      profit: 10.2,
      ctg: "other",
      type: "rare",
      price: 15000,
      icon: [thin_icon],
      max_level: 5,
      skill: 6,
      formula: [],
      description: "Древняя тонкая книга синего цвета, которая окутана тайной. Внутри неё силуэты трав и цветов, заклинания и молитвы, пробуждающие жизнь. Друид использует её, чтобы соединить атмосферу и магию, создавая волшебную ауру для растений. Каждая страница — это ключ к гармонии с природой.",
    },
    {
      id: 117,
      name: "Артефакт Желаний",
      profit: 250.99,
      ctg: "other",
      type: "rare",
      price: 30000,
      icon: [magic_lamp_icon],
      max_level: 7,
      skill: 5,
      formula: [110, 112],
      description: "Загадочный чайник желаний, испускающий мягкое свечение и окутанный магической аурой. Внутри него скрыто всё, что может пожелать сердцу владельца — от древних знаний до редких волшебных артефактов. Этот чайник, подобно коту Шредингера, таит в себе бесконечные возможности, но его содержимое остаётся неизвестным, пока крышка не будет приоткрыта. Лишь чародей, обладающий настоящим даром желания, сможет вызвать из недр чайника именно то, что ему нужно. Будь то счастье, сила или мудрость — каждый раз чайник открывает новую реальность!",
    },
    {
      id: 85,
      name: "Лиминальная сфера",
      profit: 115.7,
      ctg: "rock",
      type: "rare",
      price: 189333.16,
      icon: [misc_crystal_icon],
      max_level: 1,
      skill: 3,
      formula: [],
      description: "Кристальная сфера, сияющая таинственным светом, содержит в себе бездну магической энергии. Ее гладкая поверхность словно отражает неизведанные миры, а загадочные узоры движутся внутри, предвещая открытие портала. При взаимодействии с магическим постаментом, она активирует алтарь, который позволяет перенестись в неизведанные уголки реальности.",
    },
    {
      id: 86,
      name: "Алтарь гармонии",
      profit: 515.9,
      ctg: "artifacts",
      type: "precious",
      price: 33000,
      icon: [gozag_0_icon, gozag_1_icon, gozag_2_icon],
      max_level: 14,
      skill: 3,
      formula: [82, 15],
      description: "В центре таинственного леса сверкает магический золотой алтарь, окутанный аурой таинственности. На его вершине расположен ярко светящийся золотой кристалл, излучающий тепло и силу. Алтарь украшен древними символами и нежными цветами, создавая атмосферу умиротворения и гармонии. Это место притяжения силы природы и магии, где исполняются самые заветные желания.",
    },
    {
      id: 97,
      name: "Статуя героизма",
      profit: 719.3,
      ctg: "artifacts",
      type: "precious",
      price: 43000,
      icon: [statue_sword_icon],
      max_level: 8,
      skill: 4,
      formula: [94, 1, 4],
      description: "Изометрическая форма лезвия изящно утопает в светлых гранях, а роскошная рукоять с замысловатой резьбой выдает мастерство ремесленника. Под ярким светом, статуя кажется живой, будто готовая к бою, ее поверхность переливается, отражая отголоски древней магии и героизма.",
    },
    {
      id: 87,
      name: "Алтарь знаний",
      profit: 665.62,
      ctg: "artifacts",
      type: "precious",
      price: 46050,
      icon: [nemelex_1_icon, nemelex_2_icon, nemelex_3_icon, nemelex_4_icon, nemelex_5_icon],
      max_level: 14,
      skill: 3,
      formula: [83, 15],
      description: "Алтарь, окутанный светящимися свитками и древними книгами. Его поверхность излучает мягкий свет, наполняя воздух ощущением мудрости. Подойдя к алтарю, человек ощутит прилив ясности и понимания. Рядом с этим алтарем можно найти ответы на вопросы, которые волнуют весь мир.",
    },
    {
      id: 88,
      name: "Алтарь тьмы",
      profit: 777.17,
      ctg: "artifacts",
      type: "precious",
      price: 59100,
      icon: [qazlal_0_icon, qazlal_1_icon, qazlal_2_icon],
      max_level: 14,
      skill: 3,
      formula: [84, 15],
      description: "Алтарь Тьмы — это таинственное сооружение, сочетающее в себе магию и науку. Его мрачная архитектура излучает мистическую энергию, создавая бесконечные потоки электричества. На алтаре закодированы древние руны, которые, активируясь, вызывают яркие вспышки молний. Этот источник силы способен питать целые города, наполняя их светом и жизнью.",
    },
    {
      id: 89,
      name: "Лиминальный алтарь",
      profit: 2990.17,
      ctg: "artifacts",
      type: "majestic",
      price: 144700,
      icon: [dithmenos_icon, dithmenos_2_icon, dithmenos_3_icon],
      max_level: 15,
      skill: 3,
      formula: [85, 15],
      description: "Загадочный объект, окружённый мягким светом и непрерывно изменяющимися тенями. Его поверхность украшена причудливыми узорами, словно впитывающими энергий других миров. При прикосновении к алтарю открывается портал в лиминальные пространства — миры между сном и реальностью, полные неведомых существ и трепетных мгновений.",
    },
    {
      id: 96,
      name: "Скелет гидры",
      profit: 800.8,
      ctg: "other",
      type: "rare",
      price: 523000,
      icon: [skeleton_hydra_icon],
      max_level: 1,
      skill: 4,
      formula: [],
      description: "Древний скелет одной из самых страшных мифических существ — гидры. Ее многочисленные, разлагающиеся черепа сохранили следы битв с героями прошлого. Каждое ребро излучает холодный свет, а кости всё еще хранят ауру силы и ужаса. Этот уникальный артефакт увлекает искателей приключений и ученых в изучение загадочных мифов древности.",
    },
    {
      id: 118,
      name: "Арктическая гидра",
      profit: 734.99,
      ctg: "artifacts",
      type: 'precious',
      price: 254700,
      icon: [simulacrum_hydra_5_icon],
      max_level: 12,
      skill: 5,
      formula: [116, 117, 113],
      description: "Арктическая гидра - загадочное существо, обитающее в ледяных океанах. С 5-ю головами, каждая из которых может издавать жуткий рев, эта гидра охраняет древние тайны арктических глубин. Ее шершавые чешуи переливаются всеми оттенками голубого и белого, а ледяные водовороты, возникающие вокруг, окутаны мистическим светом, пугая искателей приключений.",
    },
    {
      id: 98,
      name: "Статуя гидры",
      profit: 2510.111,
      ctg: "artifacts",
      type: "precious",
      price: 624000,
      icon: [statue_hydra_icon],
      max_level: 6,
      skill: 4,
      formula: [94, 1, 96],
      description: "Загадочная священная статуя олицетворяющая силу и мистическую энергию. Каждый из её многоглавых шей, изогнутых вмоничном танце, кажется, живёт собственной жизнью. Она охраняет древние тайны, призывая к уважению и страху перед неведомым.",
    },
    {
      id: 99,
      name: "Скульптура Пенроуза",
      profit: 50000,
      ctg: "artifacts",
      type: "myth",
      price: 4500000,
      icon: [statue_triangle_icon],
      max_level: 4,
      skill: 4,
      formula: [94, 1, 57],
      description: 'Сотканная из магии Безмерного Завета, — величественное чудо, где законы физики теряют всякое значение. Ее изящные, словно танцующие формы вызывают ощущение невесомости, погружая зрителя в абсурдный мир, где логика не имеет власти. Каждый взгляд открывает неизведанные тайны, словно сама скульптура дышит бесконечными возможностями.',
    },
    {
      id: 90,
      name: "Алтарь божества",
      profit: 50000,
      ctg: "artifacts",
      type: "myth",
      price: 4510000,
      icon: [vehumet_1_icon, vehumet_2_icon],
      max_level: 4,
      skill: 3,
      formula: [58, 15],
      description: "Легендарный алтарь, сияющий бирюзовым светом, является проекцией мыслей владельца, открывая врата к божественному. Он переносит человека в мир мифического, где истинные чудеса оживают под искрящимися лучами древних созвездий. Этот редчайший артефакт не просто предмет, а олицетворение мечты, способное соединить душу с величием высших сил.",
    },
    {
      id: 100,
      name: "Шляпа замыслов",
      profit: 2.86,
      ctg: "clothes",
      type: "magic",
      price: 400,
      icon: [urand_high_council_icon],
      max_level: 4,
      skill: 1,
      formula: [],
      description: "Удивительная шляпа зеленого цвета, которая излучает мистическую ауру. Сплетенная из редких трав и наполненная древним волшебством, она активирует свои магические силы лишь при произнесении особых слов завета и сопровождении движением посохом. В моменты, когда природа трепещет от магии, шляпа раскрывает свои тайны, даруя обладателю невероятные способности!",
    },

    {
      id: 101,
      name: "Шляпа школы магии",
      profit: 2.983,
      ctg: "clothes",
      type: "magic",
      price: 550,
      icon: [urand_pondering_icon],
      max_level: 4,
      skill: 1,
      formula: [],
      description: "Фиолетовая шляпа мага-ученика сохраняющая в себе магическую силу. Активировать магию можно лишь произнеся заклинания и совершив особое движение посохом. При правильном сочетании слов и жестов шляпа открывает доступ к заклинаниям, помогая своему владельцу освоить волшебство и раскрыть тайны магического мира!",
    },
    {
      id: 104,
      name: "Чародейские Перчатки",
      profit: 4.8,
      ctg: "clothes",
      type: "rare",
      price: 1780.14,
      icon: [urand_fencer_icon],
      max_level: 6,
      skill: 1,
      formula: [],
      description: "В глубинах школы магии, в забытом закоулке, хранятся волшебные белые перчатки. С их помощью ученики получают доступ к древним заклинаниям и скрытым знаниям. Стоит лишь надеть их, как мир вокруг начинает светиться таинственным светом, а шепот магии заполняет воздух. Но лишь истинно смелые смогут справиться с силой, что они даруют.",
    },

    {
      id: 105,
      name: "Волшебные искры",
      profit: 3.2,
      ctg: "elements",
      type: "magic",
      price: 160.4,
      icon: [gold_sparkles_1_icon, gold_sparkles_2_icon, gold_sparkles_3_icon],
      max_level: 4,
      skill: 1,
      formula: [5, 8],
      description: "Волшебные искры витают в воздухе, словно крошечные звезды, сверкающие в ночном небе. Их нежный свет переливается всеми цветами радуги, создавая атмосферу тайны и волшебства. Каждая искра насыщена магической энергией, способной пробуждать мечты и даровать силу. Они танцуют вокруг, как духи природы, наполняя пространство уютом и гармонией.",
    },

    {
      id: 106,
      name: "Темная материя",
      profit: 4.4,
      ctg: "elements",
      type: "magic",
      price: 340.532,
      icon: [drain_0_new_icon, drain_1_new_icon, drain_2_new_icon],
      max_level: 6,
      skill: 1,
      formula: [3, 100],
      description: "Материя похожее на крошечную черную дыру. Она притягивает всё вокруг, словно магнит. Рядом с ней время искривляется, а пространство вокруг становится зыбким. Это опасный артефакт, способный поглотить душу, но и дарующий невероятные силы тем, кто осмелится управлять ею.",
    },

    {
      id: 107,
      name: "Облако волшебства",
      profit: 6.3,
      ctg: "elements",
      type: "magic",
      price: 1120.2,
      icon: [irradiate_0_icon, irradiate_1_icon, irradiate_2_icon, irradiate_3_icon],
      max_level: 6,
      skill: 1,
      formula: [103, 102],
      description: "Волшебное облако, окутывает пространство легким переливом цветов. Он медленно кружится в воздухе, излучая завораживающий аромат загадочных трав и экзотических цветов. В ткáни этого дыма спрятаны воспоминания о старинных ритуалах и заклинаниях. Прикоснувшись к нему, можно ощутить тайны древности и увидеть мигание звёзд, наполняющих ночь волшебством.",
    },

    {
      id: 108,
      name: "Огненная субстанция",
      profit: 15.3,
      ctg: "elements",
      type: "rare",
      price: 31000.2,
      icon: [flame_0_icon, flame_1_icon, flame_2_icon],
      max_level: 6,
      skill: 1,
      formula: [3, 101, 104],
      description: "Огненная субстанция источает яркий свет и тепло, словно пылающий факел. В ее центре заметны языки пламени, которые танцуют и переливаются, создавая волшебные узоры. Поверхность кажется слегка искристой, как будто состоит из мельчайших частиц золота. Несмотря на свою опасность, субстанция притягивает взгляд, маня своей красотой и энергией.",
    },

    {
      id: 109,
      name: "Хрустальная субстанция",
      profit: 15.4,
      ctg: "elements",
      type: "rare",
      price: 31000.7,
      icon: [frost_0_icon, frost_1_icon],
      max_level: 6,
      skill: 1,
      formula: [5, 101, 104],
      description: "Морозная субстанция сверкает, словно миллионы бриллиантов, укрытых инеем. В её центре чувствуются ледяные кристаллы, танцующие в унисон с лёгким ветром, создавая тонкие узоры. Поверхность блестит, как свежевыпавший снег, испуская холодное сияние. Несмотря на свою неприветливость, она притягивает взгляд, маня своей загадочной красотой и бесконечной свежестью.",
    },


    {
      id: 112,
      name: "Руна духов",
      profit: 15.2,
      ctg: "runes",
      type: "magic",
      price: 3411,
      icon: [rune_tomb_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Магическая руна, выполненная в виде золотой гробницы. В её глубинах заключены древние тайны и могущественные заклинания, способные призывать духов прошлого. При активации руна наполняет пространство энергией, позволяя пользователю взаимодействовать с невидимым миром. Лучи света, исходящие из гробницы, освещают путь к знаниям и безграничным возможностям.",
    },
    {
      id: 113,
      name: "Арктическая руна",
      profit: 1.2,
      ctg: "runes",
      type: "magic",
      price: 6488,
      icon: [rune_cocytus_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Магическая руна, заключающая в себе силу древнейших северных духов.  Прикосновение к руне дарует ясность ума и крепость духа, а её холодное сияние отражает вечную мудрость Арктики.",
    },
    {
      id: 114,
      name: "Руна пламени",
      profit: 4.2,
      ctg: "runes",
      type: "magic",
      price: 18400,
      icon: [rune_gehenna_icon],
      max_level: 1,
      skill: 5,
      formula: [],
      description: "Руна пламени, резная из дерева и коры, хранит в себе магию огня. Ее тёмная поверхность, напитанная маслом, словно дышит жаром. Она умеет извлекать жизненное пламя из пепла, восстанавливая утраченные силы. Эта руна — символ возрождения и силы, способная разжигать огонь в сердцах тех, кто ей доверится.",
    },
    {
      id: 119,
      name: "Водоворот связующий",
      profit: 2734.99,
      ctg: 'elements',
      type: "precious",
      price: 534700,
      icon: [worldbinder_icon],
      max_level: 12,
      skill: 5,
      formula: [116, 9, 114],
      description: "Водоворот связующий — оспаривание реальности, приоткрывающее врата в бездны забвения. В его тёмных глубинах хранятся души, скованных цепями заблуждений и страха. Непробиваемый туман окутывает это завихрение, проникая в сознание тех, кто осмеливается подойти ближе. Стены эфира словно шепчут имена потерянных, разносом в пространстве тихие стенания и проклятия. Этот вихрь, кружащийся в мрачных облаках, манит к себе, но тот, кто попадет в его клещи, окажется в бездне, откуда нет возврата. Исходящие оттуда образы призраков уносят в черную пропасть, оставляя лишь безмолвие в унылой ночи.",
    },
    {
      id: 121,
      name: "Шаровая молния",
      profit: 1253.66,
      ctg: "elements",
      type: "rare",
      price: 72823.55,
      icon: [orb_of_electricity_icon],
      max_level: 7,
      skill: 2,
      formula: [9, 25],
      description: "Редкий феномен, словно сгусток энергии, наполняет воздух искрами и мощью. Он порождает загадочные звуки, отдаленно напоминающие гром, и искрящиеся спирали света, танцующие в ритме заклинания. Участники этого магического зрелища ощущают прилив вдохновения и уверенности, открывая новые горизонты для изучения электрической магии и ее бесконечных возможностей.",
    },
    {
      id: 122,
      name: "Ледяной шар",
      profit: 1284.31,
      ctg: "elements",
      type: "rare",
      price: 74842.33,
      icon: [orb_of_ice_icon],
      max_level: 7,
      skill: 2,
      formula: [9, 27],
      description: "Левитирующий шар из ледяной пыли, который искрится под светом как свежевыпавший снег. Этот шар, обладая удивительной легкостью, выводит своего создателя на новые высоты знаний и вдохновения, наполняя пространство холодным, но чарующим сиянием. Ледяная магическая пыль, окруженная белоснежными облачками, становится символом могущественного магического искусства, открывающим врата в мир неизведанного.",
    },
    {
      id: 123,
      name: "Огненный шар",
      profit: 1291.1,
      ctg: "elements",
      type: "rare",
      price: 74892.12,
      icon: [orb_of_fire_new_icon],
      max_level: 7,
      skill: 2,
      formula: [9, 26],
      description: "Когда заклинание из свитка огня соприкасается с этой пылью, она превращается в огненный шар, вспыхивая ярким огнем. Этот горящий магический феномен олицетворяет соединение стихий, наполняя пространство теплом и энергией. Наблюдая за танцем огненного шара, маги ощущают не только красоту, но и силу, открывая для себя неизведанные горизонты магии и познания.",
    },
    {
      id: 124,
      name: "Водоворот тьмы",
      profit: 2523.7,
      ctg: "elements",
      type: "precious",
      price: 100000,
      icon: [maelstrom_1_icon, maelstrom_2_icon, maelstrom_3_icon, maelstrom_4_icon],
      max_level: 7,
      skill: 2,
      formula: [107, 28],
      description: "В сердце мрачного леса сверкает фиолетовый водоворот, медленно поглощая свет и звуки вокруг. Его изящные, пульсирующие вихри, словно мрак, создают иллюзию бездны, тянущей за собой души заблудших. Пыль медленно кружится, притягивая кинутое в бездну взгляды, шепча невнятные тайны о мирах, скрытых за гранью, где царит вечный сумрак.",
    },
    {
      id: 125,
      name: "Сфера разрушения",
      profit: 3623.7,
      ctg: 'elements',
      type: "precious",
      price: 250000,
      icon: [orb_of_destruction_1_icon, orb_of_destruction_2_icon],
      max_level: 7,
      skill: 2,
      formula: [107, 29],
      description: "Магическая сфера разрушения излучает ослепительный фиолетовый свет, завораживая взгляд своей невероятной красотой. Быстро вращаясь, она создает вихрь энергии, способный разрушать все на своем пути. В ее ярком свете прячутся тайные силы, которые способны как поглотить, так и трансформировать. Эта сфера символизирует мощь и хаос, привносясь в мир владеющего ей магов.",
    },
    {
      id: 126,
      name: "Огненный вихрь",
      profit: 6999.98,
      ctg: "elements",
      type: "majestic",
      price: 888787.12,
      icon: [fire_vortex_2_icon, fire_vortex_3_icon, fire_vortex_4_icon],
      max_level: 7,
      skill: 2,
      formula: [108, 30],
      description: "Огненный вихрь бушует с невообразимой яростью, разрывая воздух и испепеляя всё на своём пути. Словно живое существо, он ярко сверкает и танцует, сливая в себе цвета заката. Его скорость поразительна: вихрь становится смерчем пламени, способным разорвать реальность. Призываемый из пергамента судьбы, он служит могучим оружием, сокрушающим врагов с неумолимой силой",
    },
    {
      id: 127,
      name: "Ледяной вихрь",
      profit: 6999.99,
      ctg: "elements",
      type: "majestic",
      price: 888787.13,
      icon: [spatial_vortex_1_icon, spatial_vortex_2_icon, spatial_vortex_3_icon, spatial_vortex_4_icon],
      max_level: 7,
      skill: 2,
      formula: [109, 30],
      description: "Ледяной вихрь, вызванный заклинаниями Пергамента судьбы, порождает смерч из сверкающих кристаллов, сливающихся в единое мгновение. Он обрушивается на врагов, словно ледяной шторм, ослабляя даже самых сильных. Его вихревые силы охватывают и замораживают все на своем пути, оставляя лишь безмолвие и холод. Эта стихия, завораживающая и разрушительная, идеально передает мощь магии!",
    },
    {
      id: 120,
      name: "Несчастная звезда",
      profit: 314159.26535,
      ctg: "elements",
      type: "myth",
      price: 16180339.887,
      icon: [wretched_star_icon],
      max_level: 3,
      skill: 5,
      formula: [116, 107, 56],
      description: "В тумане ночи, где свет погас, появляется мрачное облако, пронизанное тенями. Оно шепчет забытые заклинания, искажая реальность вокруг. В его глубинах скрыта руна — ключ к потусторонним тайнам, исписываемая древними знаками. Каждый, кто осмелится коснуться её, чувствует, как мрак затягивает, погружая в мир бесконечных страхов. На грани этой тьмы виднеется несчастная звезда, таящая в себе проклятие, переливающееся всеми цветами, но никогда не приносящее света.",
    },

  ]

  export default workshopItems